[Bluemix]
  iam_url = "https://iam.test.cloud.ibm.com"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = "aaaa"
  refresh_token = ""
  pay_tier = "paid"
  containers_api_route = "https://containers.test.cloud.ibm.com"
  encryption = true
  containers_api_route_private = "https://private.containers.test.cloud.ibm.com"

[Softlayer]
  encryption = true
  softlayer_username = "username"
  softlayer_api_key = "aaaa"
  softlayer_endpoint_url = "https://api.service.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.service.softlayer.com/mobile/v3"
  softlayer_datacenter = "dal10"
  softlayer_token_exchange_endpoint_url = "https://iam.cloud.ibm.com"

[VPC]
  g2_token_exchange_endpoint_url = "https://iam.stage1.bluemix.net"
  g2_riaas_endpoint_url = "https://us-south-stage01.iaasdev.cloud.ibm.com/"
  g2_riaas_endpoint_private_url = "https://us-south-stage01.private.iaasdev.cloud.ibm.com"
  g2_resource_group_id = "g2_resource_group_id"
  g2_api_key = "aaaa"
  encryption = true
  provider_type = "g2"
  iks_token_exchange_endpoint_private_url = "https://private.containers.test.cloud.ibm.com"