[Bluemix]
  iam_url = "https://iam.cloud.ibm.com"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = "aaaaa"
  refresh_token = ""
  pay_tier = "paid"
  containers_api_route = "https://au-syd.containers.cloud.ibm.com"
  encryption = true
  containers_api_route_private = "https://private.au-syd.containers.cloud.ibm.com"

[Softlayer]
  encryption = true
  softlayer_username = ""
  softlayer_api_key = ""
  softlayer_endpoint_url = "https://api.service.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.service.softlayer.com/mobile/v3"
  softlayer_datacenter = "syd01"
  softlayer_token_exchange_endpoint_url = "https://iam.cloud.ibm.com"

[VPC]
  g2_token_exchange_endpoint_url = "https://private.iam.cloud.ibm.com"
  g2_riaas_endpoint_url = "https://au-syd.iaas.cloud.ibm.com"
  g2_riaas_endpoint_private_url = "https://au-syd.private.iaas.cloud.ibm.com"
  g2_resource_group_id = "<resouce-id>"
  g2_api_key = "aaaa"
  encryption = true
  provider_type = "g2"
  iks_token_exchange_endpoint_private_url = "https://private.au-syd.containers.cloud.ibm.com"