[Bluemix]
  iam_url = "https://iam.cloud.ibm.com"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = "aaaa"
  refresh_token = ""
  pay_tier = "paid"
  containers_api_route = "https://us-south.containers.cloud.ibm.com"
  encryption = true
  containers_api_route_private = ""

[Softlayer]
  encryption = true
  softlayer_username = ""
  softlayer_api_key = ""
  softlayer_endpoint_url = "https://api.service.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.service.softlayer.com/mobile/v3"
  softlayer_datacenter = "dal10"
  softlayer_token_exchange_endpoint_url = "https://iam.cloud.ibm.com"

[VPC]
  encryption = false