[Bluemix]
  iam_url = "https://iam.bluemix.net"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = ""
  refresh_token = ""
  pay_tier = "paid"
  containers_api_route = "https://us-south.containers.cloud.ibm.com"
  encryption = true
  containers_api_route_private = "https://private.us-south.containers.cloud.ibm.com"

[Softlayer]
  encryption = true
  softlayer_username = ""
  softlayer_api_key = ""
  softlayer_endpoint_url = "https://api.service.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.service.softlayer.com/mobile/v3"
  softlayer_datacenter = "dal10"
  softlayer_token_exchange_endpoint_url = "https://iam.bluemix.net"

[VPC]
  g2_token_exchange_endpoint_url = "https://iam.bluemix.net"
  g2_riaas_endpoint_url = "https://us-south.iaas.cloud.ibm.com:443"
  g2_riaas_endpoint_private_url = "https://us-south.private.iaas.cloud.ibm.com"
  g2_resource_group_id = ""
  g2_api_key = ""
  encryption = true
  provider_type = "g2"
  iks_token_exchange_endpoint_private_url = "https://private.us-south.containers.cloud.ibm.com"

[API]
  PassthroughSecret = ""
